version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: youtube-clone:01
    container_name: youtube-clone
    ports:
      - "8000:80"
    volumes:
      - .:/usr/share/nginx/html
